Gemfile
Gemfile.lock
app/models/user.rb
app/views/layouts/application.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20200817141944_devise_create_users.rb
db/schema.rb
test/models/user_test.rb

Bonjour Fadal,
j'espère que tu vas bien.
Francois et moi nous sommes occupés de définir le modèle User.
Nous avon trouvé judicieux d'utilisé la gem devise. Tu devrais faire un tour sur la doc si tu ne connais pas c'est très utile.
:)

francois and I did the setup of the user using the gem devise

---

app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

Hello les gars je viens d'ajouter la nav-bar , je vous laisse checker et valider  @FrancoisSommella @plernoult

Add navbar

---

app/models/facility.rb
app/models/user.rb
db/migrate/20200817155104_create_facilities.rb
db/schema.rb
test/models/facility_test.rb

j'ai créé le model facility, avec 3 validations @RedOne23 @plernoult

Model facility

---

app/controllers/facilities_controller.rb
app/views/facilities/create.html.erb
app/views/facilities/index.html.erb
app/views/facilities/new.html.erb
app/views/facilities/show.html.erb
config/routes.rb
test/controllers/facilities_controller_test.rb

contoller facilities

---

config/routes.rb

only : i/o only @plernoult @FrancoisSommella

only : i/o only

---

config/routes.rb

resources i/o ressources @FrancoisSommella @plernoult

resources i/o ressources

---

db/migrate/20200818093132_add_name_facilities.rb
db/migrate/20200818093426_add_name_to_facilities.rb
db/schema.rb

col name added to facilities @FrancoisSommella @plernoult

col name added to facilities

---

app/assets/stylesheets/components/_banner.scss
app/controllers/facilities_controller.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/facilities/new.html.erb
app/views/facilities/show.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_banner.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

New and Creates methods done @FrancoisSommella @plernoult

Def new create

---

.gitignore
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card_show.scss
app/views/facilities/show.html.erb

-la view du show est updaté avec la "trip-card" template du kitt

front pour le show updaté avec une card du kitt

---

app/views/shared/_navbar.html.erb

Tennis adds added + Logo change @FrancoisSommella @plernoult

Tennis adds added + Logo change

---

.gitignore
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card-index.scss
app/views/facilities/index.html.erb

modif index

---

app/views/facilities/index.html.erb
app/views/facilities/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

links on index?
"Back" on the show pages
and the back home buttons from the navbar
as well as the book now button from home 'page

done with links for now

---

app/assets/stylesheets/application.scss
app/views/facilities/index.html.erb
app/views/facilities/show.html.erb
app/views/shared/_navbar.html.erb

Hello derniers changement avant push Heroku @FrancoisSommella @plernoult

Changements finaux

---

app/views/facilities/show.html.erb

Hello François , 
Correction de l'erreur Avatar @FrancoisSommella

avatar delete

---

app/views/shared/_navbar.html.erb

avatar fix

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_map.scss
app/controllers/facilities_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_autocomplete.js
app/javascript/plugins/init_mapbox.js
app/models/facility.rb
app/views/facilities/_info_window.html.erb
app/views/facilities/index.html.erb
app/views/facilities/new.html.erb
config/initializers/geocoder.rb
db/migrate/20200819074934_add_coordinates_to_facility.rb
db/schema.rb
package.json
yarn.lock

Carte and autocomplete done @FrancoisSommella @plernoult

Carte and autocomplete done

---

.gitignore
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_forms.scss
app/assets/stylesheets/pages/_home.scss
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/facilities/new.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

Mise en forme formulaires @FrancoisSommella @plernoult

Mise en forme formulaires

---

app/assets/stylesheets/components/_card_show.scss
app/controllers/facilities_controller.rb
app/views/facilities/show.html.erb

-modif du controller pour la méthode show (adapté pour la map)
-modif de la view "show"

added the map to the view -show-

---

app/assets/stylesheets/components/_forms.scss
app/views/facilities/new.html.erb
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb
app/views/shared/_navbar.html.erb

vLayout search form @FrancoisSommella @plernoult

Layout search form

---

app/assets/stylesheets/components/_card-index.scss
app/views/facilities/index.html.erb

Mise en page Index

---

app/assets/stylesheets/components/_card-index.scss
app/views/facilities/index.html.erb

link on index photo card @FrancoisSommella @plernoult

link on index photo card

---

app/views/facilities/_form.html.erb

l'edit de la photo est maintenant possible dans cet version 2.0 de notre App Athletiq

Edit photo

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

j ai fix la navbar , c est bon paulo tu peus aller acheter ton kebab

fix navbar

---

app/views/facilities/show.html.erb

Correction reviews @FrancoisSommella

Correction reviews

---

app/assets/stylesheets/components/_map.scss
app/views/facilities/_info_window.html.erb

Ajout du prix sur la popup de la map

Ajout du prix sur la popup de la map

---

app/assets/stylesheets/components/_card_show.scss
app/views/facilities/show.html.erb
app/views/shared/_facility_show.erb

padding top dans la show & refacto show @FrancoisSommella @plernoult

padding top dans la show & refacto show
